#!/bin/bash
REL=${1-local}

case "$REL" in
nsg_lora_arm )
  export CC=/opt/nsgdevkit-2017-Q2/usr/bin/arm-nsg_rt-linux-gnueabi-gcc
  ERL="/opt/erlang/arm_rt_eabi/erlang-22.3.4"
  export ERTS_INCLUDE_DIR=$ERL/erts-10.7.2/include
  echo Make release nsg_lora_arm;;

local )
  echo Make release local;;
esac

export SECRET_KEY_BASE=`mix phx.gen.secret`
export MIX_ENV=prod
mix compile
npm install --prefix ./assets
npm run deploy --prefix ./assets
mix phx.digest
mix release $REL

if [[ $REL == local ]]
then
  _build/prod/rel/local/bin/local start_iex
elif [[ $REL == nsg_lora_arm ]]
then
  scp _build/prod/nsg_lora_arm-0.1.0.tar.gz root@10.0.10.155:/tmp
  ssh root@10.0.10.155 \
  "mkdir -p /usr/lib/lora; tar -C /usr/lib/lora -mxzf /tmp/nsg_lora_arm-0.1.0.tar.gz"
fi
